"""Edit PaymentCard class

Revision ID: 0bb597a2feff
Revises: 9ca4d5fdc809
Create Date: 2023-07-11 16:29:57.986655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bb597a2feff'
down_revision = '9ca4d5fdc809'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'cost')
    # ### end Alembic commands ###
