"""create PaymentCard class

Revision ID: 7dc21ed93d83
Revises: 0bb597a2feff
Create Date: 2023-07-11 16:36:52.355035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7dc21ed93d83'
down_revision = '0bb597a2feff'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentCards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('card_number', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('cvc', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('paymentCard')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paymentCard',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"paymentCard_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('card_number', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cvc', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name='paymentCard_id_user_fkey'),
    sa.PrimaryKeyConstraint('id', name='paymentCard_pkey')
    )
    op.drop_table('paymentCards')
    # ### end Alembic commands ###
